# Generated by Django 6.0.4 on 2026-05-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmada'), ('CAN', 'Cancelada'), ('FIN', 'Finalizada')], default='PEN', max_length=3)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesional')),
            ],
        ),
    ]
